openapi: 3.2.0
info:
  version: 0.25.7
  title: Unified CRM Opportunities API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: https://supaglue.com
  description: '#### Introduction


    Welcome to the Unified API (CRM) documentation. You can use this API to write to multiple third-party providers within the CRM category.


    [View common schema for CRM](https://docs.supaglue.com/platform/common-schemas/crm)


    #### Base API URL

    ```

    https://api.supaglue.io/crm/v2

    ```

    '
servers:
- url: https://api.supaglue.io/crm/v2
  description: Supaglue API
tags:
- name: Opportunities
  description: The `Opportunity` Common Object represents a "deal opportunity" in CRMs.
paths:
  /opportunities:
    parameters:
    - $ref: '#/components/parameters/x-customer-id'
    - $ref: '#/components/parameters/x-provider-name'
    post:
      operationId: createOpportunity
      summary: Create opportunity
      tags:
      - Opportunities
      security:
      - x-api-key: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                record:
                  $ref: '#/components/schemas/create_update_opportunity'
              required:
              - record
            example:
              record:
                amount: 100000
                close_date: '2023-02-27T00:00:00Z'
                description: Wants to use open source unified API for third-party integrations
                name: Needs Integrations
                stage: Closed Won
                account_id: 109c88c0-7bf4-4cd8-afbc-b51f9432ca0b
      responses:
        '201':
          description: Opportunity created
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    $ref: '#/components/schemas/created_record'
                  warnings:
                    $ref: '#/components/schemas/warnings'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '409':
          $ref: '#/components/responses/conflict'
        '422':
          $ref: '#/components/responses/unprocessableEntity'
        '499':
          $ref: '#/components/responses/remoteProviderError'
        '500':
          $ref: '#/components/responses/internalServerError'
        '501':
          $ref: '#/components/responses/notImplemented'
    get:
      operationId: listOpportunities
      summary: List opportunities
      tags:
      - Opportunities
      security:
      - x-api-key: []
      parameters:
      - $ref: '#/components/parameters/include_raw_data'
      - $ref: '#/components/parameters/read_from_cache'
      - $ref: '#/components/parameters/modified_after'
      - $ref: '#/components/parameters/page_size'
      - $ref: '#/components/parameters/cursor'
      - $ref: '#/components/parameters/associations_to_fetch'
      responses:
        '200':
          description: Paginated Leads
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: '#/components/schemas/pagination'
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/opportunity'
                required:
                - pagination
                - records
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '499':
          $ref: '#/components/responses/remoteProviderError'
        '500':
          $ref: '#/components/responses/internalServerError'
        '501':
          $ref: '#/components/responses/notImplemented'
  /opportunities/{opportunity_id}:
    parameters:
    - $ref: '#/components/parameters/x-customer-id'
    - $ref: '#/components/parameters/x-provider-name'
    - name: opportunity_id
      in: path
      required: true
      schema:
        type: string
      example: c9f58083-a370-47b5-ad02-99160ea20372
    get:
      operationId: getOpportunity
      summary: Get opportunity
      tags:
      - Opportunities
      security:
      - x-api-key: []
      parameters:
      - $ref: '#/components/parameters/include_raw_data'
      - $ref: '#/components/parameters/associations_to_fetch'
      responses:
        '200':
          description: Opportunity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/opportunity'
              examples:
                Example:
                  value:
                    account:
                      id: a329053d-bf86-4b82-8356-9e897aa7dacc
                    amount: 100000
                    close_date: '2023-02-27T00:00:00Z'
                    description: Wants to use open source unified API for third-party integrations
                    id: 1234
                    last_activity_at: '2023-02-27T00:00:00Z'
                    name: Needs third-party integrations
                    owner: 93b0c2b5-26a8-4b92-b4e5-05d764eb1119
                    created_at: '2023-02-27T00:00:00Z'
                    updated_at: '2023-02-27T00:00:00Z'
                    stage: Closed Won
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '499':
          $ref: '#/components/responses/remoteProviderError'
        '500':
          $ref: '#/components/responses/internalServerError'
        '501':
          $ref: '#/components/responses/notImplemented'
    patch:
      operationId: updateOpportunity
      summary: Update opportunity
      tags:
      - Opportunities
      security:
      - x-api-key: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                record:
                  $ref: '#/components/schemas/create_update_opportunity'
              required:
              - record
      responses:
        '200':
          description: Opportunity updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/errors'
                  warnings:
                    $ref: '#/components/schemas/warnings'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '409':
          $ref: '#/components/responses/conflict'
        '422':
          $ref: '#/components/responses/unprocessableEntity'
        '499':
          $ref: '#/components/responses/remoteProviderError'
        '500':
          $ref: '#/components/responses/internalServerError'
        '501':
          $ref: '#/components/responses/notImplemented'
components:
  parameters:
    page_size:
      name: page_size
      in: query
      schema:
        type: string
      example: 123
      description: 'Number of results to return per page. (Max: 1000)'
    cursor:
      name: cursor
      in: query
      schema:
        type: string
      example: cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw
      description: The pagination cursor value
    modified_after:
      name: modified_after
      in: query
      schema:
        type: string
        format: date-time
      description: If provided, will only return objects modified after this datetime. Datetime must be in ISO 8601 format and URI encoded.
      example: '2023-02-23T00:00:00Z'
    read_from_cache:
      name: read_from_cache
      in: query
      schema:
        type: boolean
      example: true
      description: "Whether to read from Supaglue's Managed Destination cache or to read directly from the provider. \n\n\n**NOTE**: `read_from_cache=true` requires you to have the object synced to the Supaglue Managed Destination.\n"
    x-customer-id:
      name: x-customer-id
      in: header
      schema:
        type: string
      example: my-customer-1
      description: The customer ID that uniquely identifies the customer in your application
      required: true
    associations_to_fetch:
      name: associations_to_fetch
      in: query
      schema:
        type: array
        items:
          type: string
          example: contact
      description: 'List of associated objects to attempt to fetch associations for. Only relevant for hubspot and when `read_from_cache` is false.

        '
    include_raw_data:
      name: include_raw_data
      in: query
      schema:
        type: boolean
      description: Whether to include raw data fetched from the 3rd party provider.
      example: true
    x-provider-name:
      name: x-provider-name
      in: header
      schema:
        type: string
      example: salesforce
      description: The provider name
      required: true
  responses:
    forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    conflict:
      description: Conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    remoteProviderError:
      description: Remote provider error
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    badRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    notFound:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    unprocessableEntity:
      description: Unprocessable entity
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    internalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
    notImplemented:
      description: Not implemented
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'
  schemas:
    errors:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            description: A unique identifier for the instance of the error. Provide this to support when contacting Supaglue.
            example: 9366efb4-8fb1-4a28-bfb0-8d6f9cc6b5c5
          detail:
            type: string
            description: A detailed description of the error.
            example: 'Property values were not valid: [{"isValid":false,"message":"Property \"__about_us\" does not exist","error":"PROPERTY_DOESNT_EXIST","name":"__about_us","localizedErrorMessage":"Property \"__about_us\" does not exist"}]'
          problem_type:
            type: string
            description: The Supaglue error code associated with the error.
            example: MISSING_REQUIRED_FIELD
            deprecated: true
          title:
            type: string
            description: A brief description of the error. The schema and type of message will vary by Provider.
            example: 'Property values were not valid

              '
          code:
            type: string
            description: The Supaglue error code associated with the error.
            example: MISSING_REQUIRED_FIELD
          status:
            type: string
            description: The HTTP status code associated with the error.
            example: '400'
          meta:
            type: object
            description: Additional metadata about the error.
            properties:
              cause:
                type: object
                description: The cause of the error. Usually the underlying error from the remote Provider.
                example:
                  code: 400
                  body:
                    status: error
                    message: 'Property values were not valid: [{"isValid":false,"message":"Property \"__about_us\" does not exist","error":"PROPERTY_DOESNT_EXIST","name":"__about_us","localizedErrorMessage":"Property \"__about_us\" does not exist"}]'
                    correlationId: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                    category: VALIDATION_ERROR
                  headers:
                    access-control-allow-credentials: 'false'
                    cf-cache-status: DYNAMIC
                    cf-ray: 8053d17b9dae9664-SJC
                    connection: close
                    content-length: '361'
                    content-type: application/json;charset=utf-8
                    date: Mon, 11 Sep 2023 23:51:22 GMT
                    nel: '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}'
                    report-to: '{"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v3?s=FgwuXObO%2Fz6ahUJKsxjDLaXTWjooJ8tB0w4%2B%2BKaulGStx0FGkn1PoJoOx2KrFMfihzNdfAqikq7CmgbdlmwKB8hkmp3eTb68qpg10LXFlRgiSqRhbWM7yYSfo8CXmPBc"}],"group":"cf-nel","max_age":604800}'
                    server: cloudflare
                    strict-transport-security: max-age=31536000; includeSubDomains; preload
                    vary: origin, Accept-Encoding
                    x-content-type-options: nosniff
                    x-envoy-upstream-service-time: '91'
                    x-evy-trace-listener: listener_https
                    x-evy-trace-route-configuration: listener_https/all
                    x-evy-trace-route-service-name: envoyset-translator
                    x-evy-trace-served-by-pod: iad02/hubapi-td/envoy-proxy-6c94986c56-9xsh2
                    x-evy-trace-virtual-host: all
                    x-hubspot-correlation-id: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                    x-hubspot-ratelimit-interval-milliseconds: '10000'
                    x-hubspot-ratelimit-max: '100'
                    x-hubspot-ratelimit-remaining: '99'
                    x-hubspot-ratelimit-secondly: '10'
                    x-hubspot-ratelimit-secondly-remaining: '9'
                    x-request-id: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                    x-trace: 2B1B4386362759B6A4C34802AD168B803DDC1BE770000000000000000000
              origin:
                type: string
                enum:
                - remote-provider
                - supaglue
                description: The origin of the error.
                example: remote-provider
              application_name:
                type: string
                description: The name of the application that generated the error.
                example: MyCompany Production
            required:
            - origin
            additionalProperties: true
        required:
        - id
        - detail
        - problem_type
        - title
        - code
        - status
        - meta
        example:
        - meta:
            cause:
              code: 400
              body:
                status: error
                message: 'Property values were not valid: [{"isValid":false,"message":"Property \"__about_us\" does not exist","error":"PROPERTY_DOESNT_EXIST","name":"__about_us","localizedErrorMessage":"Property \"__about_us\" does not exist"}]'
                correlationId: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                category: VALIDATION_ERROR
              headers:
                access-control-allow-credentials: 'false'
                cf-cache-status: DYNAMIC
                cf-ray: 8053d17b9dae9664-SJC
                connection: close
                content-length: '361'
                content-type: application/json;charset=utf-8
                date: Mon, 11 Sep 2023 23:51:22 GMT
                nel: '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}'
                report-to: '{"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v3?s=FgwuXObO%2Fz6ahUJKsxjDLaXTWjooJ8tB0w4%2B%2BKaulGStx0FGkn1PoJoOx2KrFMfihzNdfAqikq7CmgbdlmwKB8hkmp3eTb68qpg10LXFlRgiSqRhbWM7yYSfo8CXmPBc"}],"group":"cf-nel","max_age":604800}'
                server: cloudflare
                strict-transport-security: max-age=31536000; includeSubDomains; preload
                vary: origin, Accept-Encoding
                x-content-type-options: nosniff
                x-envoy-upstream-service-time: '91'
                x-evy-trace-listener: listener_https
                x-evy-trace-route-configuration: listener_https/all
                x-evy-trace-route-service-name: envoyset-translator
                x-evy-trace-served-by-pod: iad02/hubapi-td/envoy-proxy-6c94986c56-9xsh2
                x-evy-trace-virtual-host: all
                x-hubspot-correlation-id: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                x-hubspot-ratelimit-interval-milliseconds: '10000'
                x-hubspot-ratelimit-max: '100'
                x-hubspot-ratelimit-remaining: '99'
                x-hubspot-ratelimit-secondly: '10'
                x-hubspot-ratelimit-secondly-remaining: '9'
                x-request-id: ac94252c-90b5-45d2-ad1d-9a9f7651d7d2
                x-trace: 2B1B4386362759B6A4C34802AD168B803DDC1BE770000000000000000000
          detail: 'Property values were not valid: [{"isValid":false,"message":"Property \"__about_us\" does not exist","error":"PROPERTY_DOESNT_EXIST","name":"__about_us","localizedErrorMessage":"Property \"__about_us\" does not exist"}]'
          problem_type: MISSING_REQUIRED_FIELD
          title: 'Property values were not valid

            '
          code: MISSING_REQUIRED_FIELD
          status: '400'
          id: 9366efb4-8fb1-4a28-bfb0-8d6f9cc6b5c5
    warnings:
      type: array
      items:
        type: object
        properties:
          detail:
            type: string
          problem_type:
            type: string
          title:
            type: string
    create_update_opportunity:
      type: object
      properties:
        amount:
          type:
          - integer
          - 'null'
          example: 100000
        close_date:
          type:
          - string
          - 'null'
          example: '2022-02-10T00:00:00Z'
        description:
          type:
          - string
          - 'null'
          example: Wants to use open source unified API for third-party integrations
        name:
          type:
          - string
          - 'null'
          example: Needs Integrations
        stage:
          type: string
          example: Closed Won
        account_id:
          type:
          - string
          - 'null'
          example: 64571bff-48ea-4469-9fa0-ee1a0bab38bd
        owner_id:
          type:
          - string
          - 'null'
          example: 9f3e97fd-4d5d-4efc-959d-bbebfac079f5
        pipeline:
          type:
          - string
          - 'null'
        custom_fields:
          $ref: '#/components/schemas/custom_fields'
    pagination:
      type: object
      properties:
        next:
          type:
          - string
          - 'null'
          example: eyJpZCI6IjQyNTc5ZjczLTg1MjQtNDU3MC05YjY3LWVjYmQ3MDJjNmIxNCIsInJldmVyc2UiOmZhbHNlfQ==
        previous:
          type:
          - string
          - 'null'
          example: eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9
        total_count:
          type: number
          example: 100
      required:
      - next
      - previous
    opportunity:
      type: object
      properties:
        account_id:
          type:
          - string
          - 'null'
          example: fd089246-09b1-4e3b-a60a-7a76314bbcce
        amount:
          type:
          - integer
          - 'null'
          example: 100000
        close_date:
          type:
          - string
          - 'null'
          format: date-time
          example: '2023-02-27T00:00:00Z'
        description:
          type:
          - string
          - 'null'
          example: Wants to use open source unified API for third-party integrations
        id:
          type: string
          example: 54312
        last_activity_at:
          type:
          - string
          - 'null'
          format: date-time
          example: '2023-02-27T00:00:00Z'
        name:
          type:
          - string
          - 'null'
          example: Needs third-party integrations
        owner_id:
          type:
          - string
          - 'null'
          example: d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69
        pipeline:
          type:
          - string
          - 'null'
        stage:
          type:
          - string
          - 'null'
          example: Closed Won
        status:
          type:
          - string
          - 'null'
          example: OPEN
        created_at:
          type:
          - string
          - 'null'
          format: date-time
          example: '2023-02-27T00:00:00Z'
        updated_at:
          type:
          - string
          - 'null'
          format: date-time
          example: '2023-02-27T00:00:00Z'
        is_deleted:
          type: boolean
          example: false
        last_modified_at:
          type: string
          format: date-time
          example: '2022-02-27T00:00:00Z'
      required:
      - account_id
      - amount
      - description
      - id
      - last_activity_at
      - name
      - owner_id
      - stage
      - status
      - pipeline
      - created_at
      - updated_at
      - is_deleted
      - last_modified_at
    custom_fields:
      type: object
      additionalProperties: true
      description: Custom properties to be inserted that are not covered by the common object. Object keys must match exactly to the corresponding provider API.
    created_record:
      type: object
      properties:
        id:
          type: string
      required:
      - id
  securitySchemes:
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
      description: API key to allow developers to access the API
