openapi: 3.2.0
info:
  version: 0.25.7
  title: Management Webhook Events API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: https://supaglue.com
  description: '#### Introduction


    Welcome to the Management API documentation. You can use this API to manage customer integrations and connections.


    #### Base API URL


    ```

    https://api.supaglue.io/mgmt/v2

    ```

    '
servers:
- url: https://api.supaglue.io/mgmt/v2
  description: Supaglue API
tags:
- name: Webhook Events
paths: {}
webhooks:
  sync.complete:
    post:
      summary: Sync complete
      description: Notification of the completion of a sync
      operationId: syncComplete
      x-event-type: sync.complete
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: sync.complete
              run_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              customer_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              provider_name: salesforce
              type: object
              object_type: standard
              object: contact
              result: ERROR
              error_message: Error message
            schema:
              oneOf:
              - type: object
                title: Object Sync Complete
                properties:
                  webhook_event_type:
                    type: string
                    enum:
                    - sync.complete
                    example: sync.complete
                  run_id:
                    type: string
                    example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                  connection_id:
                    type: string
                    example: e30cbb93-5b05-4186-b6de-1acc10013795
                  customer_id:
                    type: string
                    example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                  provider_name:
                    $ref: '#/components/schemas/provider_name'
                  result:
                    type: string
                    enum:
                    - SUCCESS
                    - ERROR
                  num_records_synced:
                    type: integer
                    example: 100
                  error_message:
                    type: string
                    example: Error message
                  type:
                    type: string
                    enum:
                    - object
                  object_type:
                    type: string
                    enum:
                    - common
                    - standard
                    - custom
                  object:
                    type: string
                    example: contact
                required:
                - webhook_event_type
                - run_id
                - connection_id
                - customer_id
                - provider_name
                - result
                - type
                - object_type
                - object
              - type: object
                title: Entity Sync Complete
                properties:
                  webhook_event_type:
                    type: string
                    enum:
                    - sync.complete
                    example: sync.complete
                  run_id:
                    type: string
                    example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                  connection_id:
                    type: string
                    example: e30cbb93-5b05-4186-b6de-1acc10013795
                  customer_id:
                    type: string
                    example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                  provider_name:
                    $ref: '#/components/schemas/provider_name'
                  result:
                    type: string
                    enum:
                    - SUCCESS
                    - ERROR
                  num_records_synced:
                    type: integer
                    example: 100
                  error_message:
                    type: string
                    example: Error message
                  type:
                    type: string
                    enum:
                    - entity
                  entity_id:
                    type: string
                  entity_name:
                    type: string
                required:
                - webhook_event_type
                - run_id
                - connection_id
                - customer_id
                - provider_name
                - result
                - type
                - entity_id
                - entity_name
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  sync.paused:
    post:
      summary: Sync paused
      description: Notification after a sync is paused
      operationId: syncPaused
      x-event-type: sync.paused
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: sync.paused
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              customer_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              provider_name: salesforce
              type: object
              object_type: standard
              object: contact
            schema:
              type: object
              title: Object Sync Paused
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - sync.paused
                  example: sync.paused
                run_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                customer_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                type:
                  type: string
                  enum:
                  - object
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                  - custom
                object:
                  type: string
                  example: contact
                pause_reason:
                  type: string
              required:
              - webhook_event_type
              - connection_id
              - customer_id
              - provider_name
              - type
              - object_type
              - object
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  connection.created:
    post:
      summary: Customer connection created
      description: Notification of the creation of a connection for a customer
      operationId: connectionCreated
      x-event-type: connection.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: connection.created
              customer_id: e30cbb93-5b05-4186-b6de-1acc10013795
              provider_id: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
              category: crm
              provider_name: salesforce
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - connection.created
                  example: connection.created
                customer_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                provider_id:
                  type: string
                  example: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
                category:
                  $ref: '#/components/schemas/category'
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
              required:
              - webhook_event_type
              - customer_id
              - provider_id
              - category
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  connection.deleted:
    post:
      summary: Customer connection deleted
      description: Notification of the deletion of a connection for a customer
      operationId: connectionDeleted
      x-event-type: connection.deleted
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: connection.deleted
              connection_id: 6b0abaf8-076d-48e7-9cdf-f12c68e86e2b
              customer_id: e30cbb93-5b05-4186-b6de-1acc10013795
              provider_id: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
              category: crm
              provider_name: salesforce
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - connection.deleted
                  example: connection.deleted
                connection_id:
                  type: string
                  example: 6b0abaf8-076d-48e7-9cdf-f12c68e86e2b
                customer_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                provider_id:
                  type: string
                  example: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
                category:
                  $ref: '#/components/schemas/category'
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
              required:
              - webhook_event_type
              - connection_id
              - customer_id
              - provider_id
              - category
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.created:
    post:
      deprecated: true
      summary: Entity mapping created
      description: Notification of the creation of an entity mapping
      operationId: entityEntityMappingCreated
      x-event-type: entity.entity_mapping.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.created
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.created
                  example: entity.entity_mapping.created
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.updated:
    post:
      deprecated: true
      summary: Entity mapping updated
      description: Notification of an update to an entity mapping
      operationId: entityEntityMappingUpdated
      x-event-type: entity.entity_mapping.updated
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.updated
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.updated
                  example: entity.entity_mapping.updated
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.deleted:
    post:
      deprecated: true
      summary: Entity mapping deleted
      description: Notification of the deletion of an entity mapping
      operationId: entityEntityMappingDeleted
      x-event-type: entity.entity_mapping.deleted
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.deleted
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.deleted
                  example: entity.entity_mapping.deleted
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  object.field_mapping.created:
    post:
      deprecated: true
      summary: Object field mapping created
      description: Notification of the creation of am object field mapping
      operationId: objectFieldMappingCreated
      x-event-type: object.field_mapping.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: object.field_mapping.created
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              customer_id: c7c5204a-61d3-44a7-b581-a1f29b239f89
              provider_name: salesforce
              object_name: Contact
              object_type: common
              schema_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              result: ERROR
              error_message: Error message
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - object.field_mapping.created
                  example: object.field_mapping.created
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                customer_id:
                  type: string
                  example: c7c5204a-61d3-44a7-b581-a1f29b239f89
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                object_name:
                  type: string
                  example: Contact
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                schema_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - connection_id
              - application_id
              - customer_id
              - provider_name
              - object_name
              - object_type
              - schema_id
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  object.field_mapping.updated:
    post:
      deprecated: true
      summary: Object field mapping updated
      description: Notification of an update to an object field mapping
      operationId: objectFieldMappingUpdated
      x-event-type: object.field_mapping.updated
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: object.field_mapping.updated
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              customer_id: c7c5204a-61d3-44a7-b581-a1f29b239f89
              provider_name: salesforce
              object_name: Contact
              object_type: common
              schema_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              result: ERROR
              error_message: Error message
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - object.field_mapping.updated
                  example: object.field_mapping.updated
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                customer_id:
                  type: string
                  example: c7c5204a-61d3-44a7-b581-a1f29b239f89
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                object_name:
                  type: string
                  example: Contact
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                schema_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - connection_id
              - application_id
              - customer_id
              - provider_name
              - object_name
              - object_type
              - schema_id
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
components:
  schemas:
    category:
      type: string
      enum:
      - crm
      - engagement
      - enrichment
      - marketing_automation
      - no_category
      example: crm
    provider_name:
      type: string
      enum:
      - hubspot
      - salesforce
      - pipedrive
      - zendesk_sell
      - ms_dynamics_365_sales
      - zoho_crm
      - capsule
      - outreach
      - gong
      - apollo
      - salesloft
      - intercom
      - linear
      - clearbit
      - 6sense
      - marketo
      - salesforce_marketing_cloud_account_engagement
      - slack
      example: hubspot
  securitySchemes:
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
      description: API key to allow developers to access the API
x-webhooks:
  sync.complete:
    post:
      summary: Sync complete
      description: Notification of the completion of a sync
      operationId: syncComplete
      x-event-type: sync.complete
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: sync.complete
              run_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              customer_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              provider_name: salesforce
              type: object
              object_type: standard
              object: contact
              result: ERROR
              error_message: Error message
            schema:
              oneOf:
              - type: object
                title: Object Sync Complete
                properties:
                  webhook_event_type:
                    type: string
                    enum:
                    - sync.complete
                    example: sync.complete
                  run_id:
                    type: string
                    example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                  connection_id:
                    type: string
                    example: e30cbb93-5b05-4186-b6de-1acc10013795
                  customer_id:
                    type: string
                    example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                  provider_name:
                    $ref: '#/components/schemas/provider_name'
                  result:
                    type: string
                    enum:
                    - SUCCESS
                    - ERROR
                  num_records_synced:
                    type: integer
                    example: 100
                  error_message:
                    type: string
                    example: Error message
                  type:
                    type: string
                    enum:
                    - object
                  object_type:
                    type: string
                    enum:
                    - common
                    - standard
                    - custom
                  object:
                    type: string
                    example: contact
                required:
                - webhook_event_type
                - run_id
                - connection_id
                - customer_id
                - provider_name
                - result
                - type
                - object_type
                - object
              - type: object
                title: Entity Sync Complete
                properties:
                  webhook_event_type:
                    type: string
                    enum:
                    - sync.complete
                    example: sync.complete
                  run_id:
                    type: string
                    example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                  connection_id:
                    type: string
                    example: e30cbb93-5b05-4186-b6de-1acc10013795
                  customer_id:
                    type: string
                    example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                  provider_name:
                    $ref: '#/components/schemas/provider_name'
                  result:
                    type: string
                    enum:
                    - SUCCESS
                    - ERROR
                  num_records_synced:
                    type: integer
                    example: 100
                  error_message:
                    type: string
                    example: Error message
                  type:
                    type: string
                    enum:
                    - entity
                  entity_id:
                    type: string
                  entity_name:
                    type: string
                required:
                - webhook_event_type
                - run_id
                - connection_id
                - customer_id
                - provider_name
                - result
                - type
                - entity_id
                - entity_name
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  sync.paused:
    post:
      summary: Sync paused
      description: Notification after a sync is paused
      operationId: syncPaused
      x-event-type: sync.paused
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: sync.paused
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              customer_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              provider_name: salesforce
              type: object
              object_type: standard
              object: contact
            schema:
              type: object
              title: Object Sync Paused
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - sync.paused
                  example: sync.paused
                run_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                customer_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                type:
                  type: string
                  enum:
                  - object
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                  - custom
                object:
                  type: string
                  example: contact
                pause_reason:
                  type: string
              required:
              - webhook_event_type
              - connection_id
              - customer_id
              - provider_name
              - type
              - object_type
              - object
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  connection.created:
    post:
      summary: Customer connection created
      description: Notification of the creation of a connection for a customer
      operationId: connectionCreated
      x-event-type: connection.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: connection.created
              customer_id: e30cbb93-5b05-4186-b6de-1acc10013795
              provider_id: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
              category: crm
              provider_name: salesforce
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - connection.created
                  example: connection.created
                customer_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                provider_id:
                  type: string
                  example: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
                category:
                  $ref: '#/components/schemas/category'
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
              required:
              - webhook_event_type
              - customer_id
              - provider_id
              - category
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  connection.deleted:
    post:
      summary: Customer connection deleted
      description: Notification of the deletion of a connection for a customer
      operationId: connectionDeleted
      x-event-type: connection.deleted
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: connection.deleted
              connection_id: 6b0abaf8-076d-48e7-9cdf-f12c68e86e2b
              customer_id: e30cbb93-5b05-4186-b6de-1acc10013795
              provider_id: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
              category: crm
              provider_name: salesforce
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - connection.deleted
                  example: connection.deleted
                connection_id:
                  type: string
                  example: 6b0abaf8-076d-48e7-9cdf-f12c68e86e2b
                customer_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                provider_id:
                  type: string
                  example: 5a4dbac6-3a56-4ad9-8aa3-e7b7f00be024
                category:
                  $ref: '#/components/schemas/category'
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
              required:
              - webhook_event_type
              - connection_id
              - customer_id
              - provider_id
              - category
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.created:
    post:
      deprecated: true
      summary: Entity mapping created
      description: Notification of the creation of an entity mapping
      operationId: entityEntityMappingCreated
      x-event-type: entity.entity_mapping.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.created
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.created
                  example: entity.entity_mapping.created
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.updated:
    post:
      deprecated: true
      summary: Entity mapping updated
      description: Notification of an update to an entity mapping
      operationId: entityEntityMappingUpdated
      x-event-type: entity.entity_mapping.updated
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.updated
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.updated
                  example: entity.entity_mapping.updated
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  entity.entity_mapping.deleted:
    post:
      deprecated: true
      summary: Entity mapping deleted
      description: Notification of the deletion of an entity mapping
      operationId: entityEntityMappingDeleted
      x-event-type: entity.entity_mapping.deleted
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: entity.entity_mapping.deleted
              entity_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              connection_id: a7052919-e024-4985-bd08-856056b66f59
              customer_id: 1a2b3c4d5e6f
              provider_name: salesforce
              object_name: opportunity
              object_type: standard
              result: SUCCESS
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - entity.entity_mapping.deleted
                  example: entity.entity_mapping.deleted
                entity_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                connection_id:
                  type: string
                  example: a7052919-e024-4985-bd08-856056b66f59
                customer_id:
                  type: string
                  example: 1a2b3c4d5e6f
                provider_name:
                  type: string
                  example: salesforce
                object_name:
                  type: string
                  example: opportunity
                object_type:
                  type: string
                  enum:
                  - standard
                  - custom
                  example: standard
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - entity_id
              - application_id
              - connection_id
              - customer_id
              - provider_name
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  object.field_mapping.created:
    post:
      deprecated: true
      summary: Object field mapping created
      description: Notification of the creation of am object field mapping
      operationId: objectFieldMappingCreated
      x-event-type: object.field_mapping.created
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: object.field_mapping.created
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              customer_id: c7c5204a-61d3-44a7-b581-a1f29b239f89
              provider_name: salesforce
              object_name: Contact
              object_type: common
              schema_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              result: ERROR
              error_message: Error message
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - object.field_mapping.created
                  example: object.field_mapping.created
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                customer_id:
                  type: string
                  example: c7c5204a-61d3-44a7-b581-a1f29b239f89
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                object_name:
                  type: string
                  example: Contact
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                schema_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - connection_id
              - application_id
              - customer_id
              - provider_name
              - object_name
              - object_type
              - schema_id
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  object.field_mapping.updated:
    post:
      deprecated: true
      summary: Object field mapping updated
      description: Notification of an update to an object field mapping
      operationId: objectFieldMappingUpdated
      x-event-type: object.field_mapping.updated
      tags:
      - Webhook Events
      requestBody:
        content:
          application/json:
            example:
              webhook_event_type: object.field_mapping.updated
              connection_id: e30cbb93-5b05-4186-b6de-1acc10013795
              application_id: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
              customer_id: c7c5204a-61d3-44a7-b581-a1f29b239f89
              provider_name: salesforce
              object_name: Contact
              object_type: common
              schema_id: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
              result: ERROR
              error_message: Error message
            schema:
              type: object
              properties:
                webhook_event_type:
                  type: string
                  enum:
                  - object.field_mapping.updated
                  example: object.field_mapping.updated
                connection_id:
                  type: string
                  example: e30cbb93-5b05-4186-b6de-1acc10013795
                application_id:
                  type: string
                  example: 7bfcc74d-c98b-49de-8e8f-3dc7a17273f6
                customer_id:
                  type: string
                  example: c7c5204a-61d3-44a7-b581-a1f29b239f89
                provider_name:
                  $ref: '#/components/schemas/provider_name'
                object_name:
                  type: string
                  example: Contact
                object_type:
                  type: string
                  enum:
                  - common
                  - standard
                schema_id:
                  type: string
                  example: 2fdbd03d-11f2-4e66-a5e6-2b731c71a12d
                result:
                  type: string
                  enum:
                  - SUCCESS
                  - ERROR
                error_message:
                  type: string
                  example: Error message
              required:
              - webhook_event_type
              - connection_id
              - application_id
              - customer_id
              - provider_name
              - object_name
              - object_type
              - schema_id
              - result
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
